language: node_js
sudo: false
node_js:
  - 4
  - node
notifications:
  email:
    on_success: change
    on_failure: always
before_script:
  - node --version | grep -q "v4." || npm install -g npm
  - TRAVIS=1 ./setup.sh
